#include <iostream>
#include <mutex>
#include <string>
#include <cstring>

#include "modelState.h"
#include "testResults.h"
#include "cachePaths.h"
#include "runFull.h"
#include "runFromCache.h"

ModelState MODEL_STATE;
TestResults TEST_RESULTS;
CachePaths CACHE_PATHS;
std::mutex m;
double NUM_THREADS;
int K_FOLDS = 10;
size_t MIN_CLASS_MEMBERS = 30;
size_t MAX_CLASS_MEMBERS = 1000;

void printBasicHelp() {
    std::string helpKFoldMsg = "Usage (k fold cross validation): ./cpv [-H] weightScheme pvalueThreshold featureWeighting neighborsChecked minSameClass "
        "doNOTATesting [sigmoidFitsFilepath NOTAPointsFilepath] datasetFilepath cacheDirectory mode\n"
        "\t -H: display more detailed help message\n"
        "\t weightScheme: {\"squared\", \"linear\", \"unweighted\", \"cube root\"}\n"
        "\t pvalueThreshold: {\"per class\"}\n"
        "\t featureWeighting: {0, 1}\n"
        "\t neighborsChecked: non negative integer\n"
        "\t minSameClass: non negative integer\n"
        "\t doNOTATesting: {0, 1}\n"
        "\t sigmoidFitsFilepath: {file containing sigmoid fits that was output by a previous run, \"\"}\n"
        "\t NOTAPointsFilepath: {file containing none of the above (NOTA) points generated by a previous run, \"\"}\n"
        "\t datasetFilepath: file containing dataset to run k fold cross validation on\n"
        "\t cacheDirectory: folder where output logs from training and testing will be stored\n"
        "\t mode: {\"k fold\"}\n";

    std::string helpProductionMsg = "Usage (production): ./cpv [-H] pvalueThreshold featureWeighting neighborsChecked "
        "minSameClass sigmoidFitsFilepath datasetFilepath testSetFilepath cacheDirectory mode\n"
        "\t -H: display more detailed help messsage\n"
        "\t pvalueThreshold: {\"per class\"}\n"
        "\t featureWeighting: {0, 1}\n"
        "\t neighborsChecked: non negative integer\n"
        "\t minSameClass: non negative integer\n"
        "\t sigmoidFitsFilepath: file containing sigmoid fits that was output by a previous run\n"
        "\t datasetFilepath: file containing \"knowledge base\" of model\n"
        "\t testSetFilepath: file containing unknown datapoints\n"
        "\t cacheDirectory: folder where output logs from testing will be stored\n"
        "\t mode: {\"production\"}\n";

    std::cout << helpKFoldMsg;
    std::cout << helpProductionMsg;
}

void printDetailedHelp() {
    std::string helpKFoldMsg = "Usage (k fold cross validation): ./cpv [-H] weightScheme pvalueThreshold featureWeighting neighborsChecked minSameClass "
        "doNOTATesting [sigmoidFitsFilepath NOTAPointsFilepath] datasetFilepath cacheDirectory mode\n"
        "\t -H: Display more detailed help message.\n"
        "\t weightScheme {\"squared\", \"linear\", \"unweighted\", \"cube root\"}: Weight assigned to points in the "
        "empirical distribution curve (ECDF) during curve fitting, as a function of nearest neighbor distance. "
        "Recommended to choose \"squared.\"\n"
        "\t pvalueThreshold {\"per class\"}\n"
        "\t featureWeighting {0, 1}: Boolean value for whether to apply feature weighting during nearest neighbor "
        "distance calculations.\n"
        "\t neighborsChecked {non negative integer}: Number of global nearest neighbors to find for \"voting off the "
        "island.\" 5 is generally a good choice.\n"
        "\t minSameClass {non negative integer}: Minimum number of global nearest neighbors required to keep a datapoint "
        "during \"voting off the island.\" 3 is generally a good choice. 0 is the equivalent of disabling \"voting off the "
        "island,\" and it is recommended to also pass 0 for neighborsChecked in this case.\n"
        "\t doNOTATesting {0, 1}: Boolean value for whether NOTA points should be tested on\n"
        "\t sigmoidFitsFilepath: File containing sigmoid fits that were output by a previous run or \"\" if the "
        "argument is unused. Providing sigmoid fits will cause the fitting procedure to be skipped.\n"
        "\t NOTAPointsFilepath: File containing none of the above (NOTA) points generated by a previous run or \"\" "
        " if the argument is unused. These NOTA points will be used instead of generating new points.\n"
        "\t datasetFilepath: File containing dataset to run k fold cross validation on. The first row must be the "
        "header; the first column must be the class column; and subsequent columns must be the features. Prepending "
        "\"nonNum\" to a column name will cause that column and all subsequent columns to be disregarded.\n"
        "\t cacheDirectory: Folder where output logs from training and testing will be stored.\n"
        "\t mode {\"k fold\"}\n\n"
        "Recommendation: Redirect the standard output to a file to save additional helpful information, including "
        "confusion matrices for the classes and \"none of the above\" (NOTA) points.\n";

    std::string helpProductionMsg = "Usage (production): ./cpv [-H] pvalueThreshold featureWeighting neighborsChecked "
        "minSameClass sigmoidFitsFilepath datasetFilepath testSetFilepath cacheDirectory mode\n"
        "\t -H: Display more detailed help message.\n"
        "\t pvalueThreshold {\"per class\"}\n"
        "\t featureWeighting {0, 1}: Boolean value for whether to apply feature weighting during nearest neighbor "
        "distance calculations.\n"
        "\t neighborsChecked {non negative integer}: Number of global nearest neighbors to find for \"voting off the "
        "island.\" 5 is generally a good choice.\n"
        "\t minSameClass {non negative integer}: Minimum number of global nearest neighbors required to keep a datapoint "
        "during \"voting off the island.\" 3 is generally a good choice. 0 is the equivalent of disabling \"voting off the "
        "island,\" and it is recommended to also pass 0 for neighborsChecked in this case.\n"
        "\t sigmoidFitsFilepath: File containing sigmoid fits that were output by a previous run.\n"
        "\t datasetFilepath: File containing datapoints that will be used during nearest neighbor distance calculations "
        "for test points. The first row must be the header; the first column must be the class column; and subsequent "
        "columns must be the features. Prepending \"nonNum\" to a column name will cause that column and all subsequent "
        "columns to be disregarded.\n"
        "\t testSetFilepath: File containing unseen datapoints that p values will be calculated for. It must follow "
        "the same format as the file for the \"datasetFilepath\" argument, although the value in the class column "
        "is unused and may be left as an empty string. Unlike with k fold cross validation, datapoints in this file are "
        "read into memory one at a time, allowing for testing on arbitrarily large amounts of data.\n"
        "\t cacheDirectory: Folder where output logs from testing will be stored.\n"
        "\t mode {\"production\"}\n\n"
        "The standard output primarily consists of the calculated p values, which will already be written to a file "
        "in the folder specified by the \"cacheDirectory\" argument, so redirecting the standard output to a file is "
        "not necessary.\n";

    std::cout << helpKFoldMsg;
    std::cout << std::endl << std::endl;
    std::cout << helpProductionMsg;
}

int main(int argc, char* argv[]) {
    switch (argc) {
        case 4:
            runFromPValues(argv);
            break;
        case 5:
            runFromNNDistances(argv);
            break;
        case 10:
            if (std::strcmp(argv[9], "production") == 0) {
                runProduction(argv);
            }
            else if (std::strcmp(argv[9], "k fold") == 0) {
                runFull(argc, argv);
            }
            else {
                std::cerr << "Invalid Argument: mode must be one of {\"production\", \"k fold\"}" << std::endl;
                std::exit(0);
            }
            break;
        case 12:
            if (std::strcmp(argv[11], "k fold") == 0) {
                runFull(argc, argv);
            }
            else {
                std::cerr << "Invalid Argument: mode must be one of {\"k fold\"}" << std::endl;
                std::exit(0);
            }
            break;
        default:
            if (argc > 1 && std::strcmp(argv[1], "-H") == 0) {
                printDetailedHelp();
            }
            else {
                printBasicHelp();
            }
    } 
}
